### ISSUE TITLE
Support for multiple properties and merged style rules.

### ISSUE THREAD

**Issue by AshHeskes** [JoelSutherland/LESS-Prefixer#22]
It would be useful if you allowed support for passing multiple properties to the mixins.

e.g

	.foo {
		.transition( opacity .2s ease-out, background-color .5s ease-in );	
	}
	
You can also enable this using the less [merge feature](http://lesscss.org/features/#merge-feature). Which will allows multiple mixin declarations to create a single comma separated rule.

e.g.

	.foo {
		.transition( opacity .2s ease-out );
		.transition( background-color .5s ease-in );
	}
	
Would output: (prefixed properties ignored for brevity)

	.foo {
		transition: opacity .2s ease-out, background-color .5s ease-in;	
	}
	
The advantage of the merge approach is that it's then possible for other mixins and hard coded style rules to interact with those of prefixer.

e.g

	.foo {
		.transition( opacity .2s ease-out );
		transition+: -webkit-transform 1s ease-in;
		.coolEasingMixin( left .3s elastic );
	}
	
Would output:

	.foo {
		transition : opacity .2s ease-out, -webkit-transform 1s ease-in, left .3s cubic-bezier(1.000, -0.600, 0.115, 1.460);
	}
	
Personally I would enable support for both methods.

**Comment by woble** [comment]
I just use escape function in all of my mixins and parse argument as a string:

````less
.transition(@transition) {
    -webkit-transition: e(@transition);
       -moz-transition: e(@transition);
        -ms-transition: e(@transition);
            transition: e(@transition);
}
````

````less
.foo {
    .transition('opacity .2s ease, background-color .3s ease-out');
}
````

if you need to use variable calculations then do it outside the mixin first.
````less
.foo {
    @time: .2s - .1s;
    .transition('opacity @{time} ease, background-color .3s ease-out');
}
````
Your solution doesn't work on all properties.
````less
.transition-property(@transition-property) {
    -webkit-transition-property: @transition-property;
       -moz-transition-property: @transition-property;
        -ms-transition-property: @transition-property;
         -o-transition-property: @transition-property;
            transition-property: @transition-property;
}

.foo {
    .transition-property(opacity);
    .transition-property(background-color);
    .transition-property(color);
}
````
Outputs to
````css
.foo {
  -webkit-transition-property: opacity;
     -moz-transition-property: opacity;
      -ms-transition-property: opacity;
       -o-transition-property: opacity;
          transition-property: opacity;
  -webkit-transition-property: background-color;
     -moz-transition-property: background-color;
      -ms-transition-property: background-color;
       -o-transition-property: background-color;
          transition-property: background-color;
  -webkit-transition-property: color;
     -moz-transition-property: color;
      -ms-transition-property: color;
       -o-transition-property: color;
          transition-property: color;
}
````
