### ISSUE TITLE
Outdated documentation on "box-shadow"?

### ISSUE THREAD

**Issue by JanisE** [JoelSutherland/LESS-Prefixer#54]
In documentation, it is written that box-shadow should get prefixes:

So you type this:

```css
div {
	.box-shadow(0px 0px 10px rgba(255,0,0,.5));
}
```
and you get this through the beauty of LESS:
```css
div {
	-webkit-box-shadow: 0px 0px 10px rgba(255,0,0,.5);
	-moz-box-shadow: 0px 0px 10px rgba(255,0,0,.5);
	box-shadow: 0px 0px 10px rgba(255,0,0,.5);
}
```

However, in reality, nothing is added – it results in a simple
```css
div {
        box-shadow: 0px 0px 10px rgba(255,0,0,.5);
}
```

In the code, I see that `box-shadow` is really not getting any prefixes. Why is that? And the documentation/readme should be updated as well.
